# We're using version 3.7 of the Docker Compose file format
version: "3.7"

# Define services/containers
services:

  phpapache:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80

  mysql:
    image: mysql:8.0.19
    # Connect to "my-network" network, as defined below
    networks:
      - my-network
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ./mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    networks:
      - my-network
    # Map port 8080 on the host to port 80 inside the container
    # HOST_PORT:CONTAINER_PORT
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    # Wait for "mysql" container to start first
    depends_on:
      - mysql

# Define networks
networks:
  my-network: